sudo: required
services:
  - docker

before_install:
  - docker build -t montmirail/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run montmirail/react-test npm test -- --coverage

after_success:
  - docker build -t montmirail/complex-client ./client
  - docker build -t montmirail/complex-nginx ./nginx
  - docker build -t montmirail/complex-server ./server
  - docker build -t montmirail/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#  - docker login -u "$DOCKER_ID" --password-stdin
  - docker push montmirail/complex-client
  - docker push montmirail/complex-nginx
  - docker push montmirail/complex-server
  - docker push montmirail/complex-worker